### ISSUE TITLE
System representation or compute graph should be insensitive to atom pairs with distances greater than cutoff

### ISSUE THREAD

**Issue by wiederm** [choderalab/modelforge#103]
As discussed with @jchodera, the assumption that the neighbor list returns atom pairs with distances below the cutoff distance might be violated under specific scenarios. The features produced by the neural networks should be insensitive to these atom pairs.

**Comment by chrisiacovella** [comment]
Can you expand further on what this means?  I'm not quite understanding.

**Comment by wiederm** [comment]
A given neighbor list implementation might not always return atom pairs with distances strictly below the cutoff distance. Therefore, the system representation of the neural network potential should ignore such atom pairs. 

This is already the case for models representing their environment using atom-centered radial symmetry functions: the radial basis function goes to zero as the cutoff is approached. For other representations we need to make sure that a similar cutoff to the *representation* is applied.

**Comment by chrisiacovella** [comment]
Ah, now I understand.  The way I implemented the Chiron neighbor list, it returns a mask for the neighbor list (allowing for fixed size of the array) and I use this mask as a pre-factor of the potential energy (i.e., it will multiply anything beyond the cutoff with 0 so it does not contribute to the energy, anything within the cutoff is by 1).  I was thinking about how this would translate/be implemented for the NNPs.

**Comment by wiederm** [comment]
I think this issue has become more relevant since we realized that some of the neighborlist implementations are not able to compute distances using the minimum image convention.

**Comment by wiederm** [comment]
This has been resolved for all architectures. Edge features that contain signals for distances greater than the cutoff are set to zero by using cutoff (annealing) functions for each edge representation.
