### ISSUE TITLE
Checksum of downloaded file does not match expected checksum

### ISSUE THREAD

**Issue by wiederm** [choderalab/modelforge#140]
Running the training script in the `ref-toml` branch with the attached config file returns an checksum error for the SPICE2 dataset:
`Exception: Checksum of downloaded file 0c2808134496aacb6ec775d74cf86090 does not match expected checksum 244a559a6062bbec5c9cb49af036ff7d.`

The error should be reproducible running:
`python perform_training.py ani2x_spice.toml`

I have attached the script and the toml file.

[training.zip](https://github.com/user-attachments/files/15526173/training.zip)

**Comment by wiederm** [comment]
@chrisiacovella , can you please take a look at this?

**Comment by chrisiacovella** [comment]
I'll take a look at this shortly (figure out if I put the wrong checksum in the yaml file, or failed to upload the right file to dropbox).  Related, I'll create a simple non-CI test script that downloads all the datasets, since the full datasets are too large to test this.

**Comment by wiederm** [comment]
Thanks! That is a great idea!

I am using the ANI-2x dataset now, this works as expected.

**Comment by chrisiacovella** [comment]
I addressed this in #145  and also added in a pytest script to download all of the datasets (optional).  I actually don't think pytest is the best option for this; we might just make a class within the datasets module that allows us to interrogate (e.g., list available versions from the yaml files) with a option to check the download of a given dataset (or all).
