### ISSUE TITLE
Advanced indexing slower than torch.gather on GPU

### ISSUE THREAD

**Issue by ArnNag** [choderalab/modelforge#143]
While going through the SpookyNet code, I noticed that all places in the code that involve computing edge features from a list of node features and lists of source and destination indices select between using either advanced indexing or `torch.gather` based on whether the tensors are on CPU or GPU:
https://github.com/search?q=repo%3AOUnke%2FSpookyNet+%22gathering+is+faster+on+GPUs%22&type=code

We use advanced indexing for this purpose in PaiNN, SAKE, and PhysNet:
https://github.com/choderalab/modelforge/blob/21d0e792aac539a571fc073b29dd0cb71cd0c3e9/modelforge/potential/painn.py#L378
https://github.com/choderalab/modelforge/blob/21d0e792aac539a571fc073b29dd0cb71cd0c3e9/modelforge/potential/physnet.py#L297
https://github.com/choderalab/modelforge/blob/21d0e792aac539a571fc073b29dd0cb71cd0c3e9/modelforge/potential/schnet.py#L304
https://github.com/choderalab/modelforge/blob/21d0e792aac539a571fc073b29dd0cb71cd0c3e9/modelforge/potential/sake.py#L522

Perhaps these potentials could be optimized on GPU by rewriting these with `torch.gather`.

**Comment by wiederm** [comment]
Thank you for raising this! I will profile and rewrite these indexing operations!

**Comment by ArnNag** [comment]
Is the neighborlist construction done on GPU? Perhaps there is also a performance difference between `torch.masked_select` and indexing by a tensor of Booleans.

**Comment by wiederm** [comment]
I think the difference in speed of `gather` and integer indexing has been reported in this issue: https://github.com/pytorch/pytorch/issues/15245 . 
It seems that, as of 2019, `torch.gather` and integer indexing should have similar performance on CUDA.

We have two scripts in PR #142 that profile a single pass and a single epoch, I will add a notebook that uses the [pytorch.benchmark.timeit](https://pytorch.org/tutorials/recipes/recipes/benchmark.html#benchmarking-with-torch-utils-benchmark-timer) to have the tools to test these kind of questions.

**Comment by wiederm** [comment]
After timing the different operations, I think that they are performing similarly. I have used this [notebook](https://github.com/choderalab/modelforge/blob/ref-profile/notebooks/benchmark.ipynb) on CUDA with 1-4 threads and the results seem independent of the threads. 
This is the output for CUDA using a single thread:

```
Gather:
<torch.utils.benchmark.utils.common.Measurement object at 0x7f413f4e35d0>
index_using_gather(tensor.clone(), indices.clone())
setup: from __main__ import index_using_gather, tensor, indices
  23.64 us
  1 measurement, 10000 runs , 4 threads
Integer Indexing:
<torch.utils.benchmark.utils.common.Measurement object at 0x7f413e1f5590>
index_using_integral_indexing(tensor.clone(), indices.clone())
setup: from __main__ import index_using_integral_indexing, tensor, indices
  18.81 us
  1 measurement, 10000 runs , 4 threads

```
