### ISSUE TITLE
openff-units Version Issue

### ISSUE THREAD

**Issue by MarshallYan** [choderalab/modelforge#184]
#181 openff-units 0.2.2 requires pint version to be <=0.23. So directly install pint (which is currently 0.24.1) doesn't work, and will cause error: `E   ModuleNotFoundError: No module named 'pint.measurement'`.

**Comment by wiederm** [comment]
Thanks for raising this @MarshallYan ! I haven't experienced this issue myself, but I will investigate.

**Comment by wiederm** [comment]
This has been pinned now,  thanks for raising this @MarshallYan
