### ISSUE TITLE
Missing keys in Pydantic BaseModel

### ISSUE THREAD

**Issue by wiederm** [choderalab/modelforge#233]
I've noticed that if we have operations defined in the TOML files that don't have a corresponding key in the Pydantic `BaseModel`, these keywords will be silently ignored. This behavior is unexpected in my opinion. I would have expected it to throw an error. I think we should change this current behavior so that it throws an error if operations aren't parsed.

**Comment by chrisiacovella** [comment]
This is a simple fix:  we'll just want to set `extra="forbid"` in the ConfigDict (e.g., in the ParamBase class)

**Comment by wiederm** [comment]
Ah, that is easy enough! I will open a PR!
