### ISSUE TITLE
Training stuck in the current main branch

### ISSUE THREAD

**Issue by MarshallYan** [choderalab/modelforge#249]
When I try to train a model on MacOS (specifically TensorNet and ANI2x), it gets stucked when calculating pairlist for the dataset.

**Comment by chrisiacovella** [comment]
I think this is an issue with how multiprocessing is implemented in the PyTorch data loader on Mac OS.  If we do not wrap the data loader in something like below, it will end up hanging.  

` if __name__ == "__main__":
`

However, implementing this, I see a possible bug about catting empty tensors (which seems to be causing problems on Mac OS not on linux).

**Comment by wiederm** [comment]
We are currently not supporting MacOs for training.
