### ISSUE TITLE
Add reference energy

### ISSUE THREAD

**Issue by chrisiacovella** [choderalab/modelforge#33]
The reference energy for each molecule need to be added to the QM9 and ani1x datasets.  
- Reference energies for individual atoms for QM9 are defined in the SI material on figshare: 
https://springernature.figshare.com/articles/dataset/Atomref_Reference_thermochemical_energies_of_H_C_N_O_F_atoms_/1057643?backTo=/collections/Quantum_chemistry_structures_and_properties_of_134_kilo_molecules/978904
- Still need to find reference energies for the ANI-1x dataset.  
  -  When doing this, should also probably split the dataset to produce separate ANI-1x and ANI-1ccx files to avoid users mixing and matching different computations.

**Comment by wiederm** [comment]
In PR#63 we use a least square fit to obtain self energies from a dataset. These are not necessarily physical (i.e., these might not be the correct QM level of theory atomize energies), but this shouldn't matter as long as they are reasonably close.

**Comment by wiederm** [comment]
This has been resolved in PR #73
